# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daf6093d3be3dfa47be2f85c085c9bee161cff41bcbbd147e54be62d1356ccfb6dabb829b621bc1017067568caabec7091b868a4198de1677c133fe709e7e30a

test:
  secret_key_base: 3af84be4a8aca9616c30772c2037358be1bd5470e450a558d0dac6942f1a058caf19332a717b8178b6184979e1eb1e37ee72e1c9a3740e8337b502ffb80ec1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
